### ISSUE TITLE
Bug if MFA not set up

### ISSUE THREAD

**Issue by BJReplay** [tomhollander/TeslaAuth#1]
Thanks for this - life saver!  This helped me get my VB.Net service back up and running.

I think there is a bug, though when you don't have MFA set up - the check at https://github.com/tomhollander/TeslaAuth/blob/master/library/TeslaAuthHelper.cs#L168 throws an error when the response code is the redirect - this test should (I think) only throw the error when it's not a success code and it is not a redirect.

Sorry for not submitting a pull request - the best I can do is read C# and use it to write VB.Net.

**Comment by tomhollander** [comment]
Thanks for pointing out the bug @BJReplay.  I have MFA on for my account but I did do some testing with MFA off. However I did notice some behavioural differences when running on .NET core under WSL vs regular .NET, and this may be one of them. I'll do some more testing and push out a new version.

**Comment by tomhollander** [comment]
This is now fixed.
