### ISSUE TITLE
Tesla SSO page changes: Duplicate fields, then ReCAPTCHA?

### ISSUE THREAD

**Issue by briangru** [tomhollander/TeslaAuth#23]
I noticed we're getting an ArgumentException introducing the same key multiple times to a dictionary in InitializeLoginAsync.  Looks like Tesla changed the login form to add the same fields twice in some places.  If you run the console app and try to log in, this shows up.

Tesla's web page contains this:

```
        <form method="post">
          <input type="hidden" name="_csrf" value="D61EEW6H-pOBVZigzY8GyaUOGZ66nIC81P9w" />
          <input type="hidden" name="_phase" value="authenticate" />
          <input type="hidden" name="cancel" value="1" />
          <input type="hidden" name="transaction_id" value="ZiFszIwo" />
```

And later, this:

```
        <div class="single-column-form-wrapper">
          <form method="post" id="form" class="sso-form sign-in-form">
            <input type="hidden" name="_csrf" value="D61EEW6H-pOBVZigzY8GyaUOGZ66nIC81P9w" />
            <input type="hidden" name="_phase" value="authenticate" />
            <input type="hidden" name="_process" value="1" />
            <input type="hidden" name="transaction_id" value="ZiFszIwo" />
            <input type="hidden" name="cancel" value="" id="form-input-cancel" />

```

I first noticed this with the _csrf field.  I changed InitializeLoginAsync to just overwrite, like this:

```
        async Task InitializeLoginAsync(HttpClient client, CancellationToken cancellationToken)
        {
            [..snip..]
            var hiddenFields = Regex.Matches(resultContent, "type=\\\"hidden\\\" name=\\\"(.*?)\\\" value=\\\"(.*?)\\\"");
            var formFields = new Dictionary<string, string>();
            foreach (Match match in hiddenFields)
            {
                // Around October 2021 Tesla started showing duplicate hidden fields in the page.  They had the same value.
                formFields[match.Groups[1].Value] = match.Groups[2].Value;
            }
```

However, this doesn't work.  I get the extremely ambiguous error "Expected redirect did not occur" from GetAuthorizationCodeAsync.  This was on an account with no MFA enabled.  Looking more closely, it looks like a reCAPTCHA problem.  Thoughts?

![image](https://user-images.githubusercontent.com/2916328/136631546-491d7041-53ca-4e3f-bbd4-bfc23bd481a5.png)

**Comment by tomhollander** [comment]
The library doesn't work when the CAPTCHA is displayed. I recommend using the browser assisted flow where possible to avoid the problem.
