### ISSUE TITLE
FWIW - JS translation of this library

### ISSUE THREAD

**Issue by ArthurD** [tomhollander/TeslaAuth#24]
Hi -- thank you so much for this repo, was super helpful and it made it MUCH easier for me to translate it to JS.  Thank you!  :)

I've published the JS translation of the lib here:  https://github.com/ArthurD/TeslaAuthJS

It allowed me to get a nice menubar app running that shows my my solar & battery status!  :)
<img width="392" alt="Screen Shot 2022-02-22 at 3 34 25 PM" src="https://user-images.githubusercontent.com/109532/155237751-b5d3d821-358a-4c5f-bd02-f3bf2cad92a5.png">

Best,

-AD

**Comment by tomhollander** [comment]
Awesome, great work! If you haven't already done so, you may also want to check out https://github.com/tomhollander/PowerwallCompanionX for some more examples of how I interact with the Powerwall APIs.
