### ISSUE TITLE
ExchangeAccessTokenForBearerTokenAsync method not working properly

### ISSUE THREAD

**Issue by hugo-dias** [tomhollander/TeslaAuth#28]
It seems that something changed on Tesla side... TeslaAuth library was working properly, but right now I'm getting
**{"response":"unsupported_authentication_method_-_please_update_to_the_latest_version"}**

on **https://owner-api.teslamotors.com/oauth/token** call inside **ExchangeAccessTokenForBearerTokenAsync** method.

Can you help?
Thanks!

**Comment by tomhollander** [comment]
Are you using the latest version of the library? The call to `ExchangeAccessTokenForBearerTokenAsync` was removed from the browser-assisted flow. The code is still wired up to the headless flow, but that code path hasn't been reliable for some time.
