### ISSUE TITLE
About UWP version of TeslaAuth

### ISSUE THREAD

**Issue by mediaexplorer74** [tomhollander/TeslaAuth#29]
Hi. 

Please make UWP version of TeslaAuth if You can.
Cheers up :)

Best, 
  mediaexplorer

**Comment by tomhollander** [comment]
The library is compiled with .NET Standard which can be used by UWP apps. Please see https://github.com/tomhollander/PowerwallCompanion as an example.

**Comment by mediaexplorer74** [comment]
> The library is compiled with .NET Standard which can be used by UWP apps. Please see https://github.com/tomhollander/PowerwallCompanion as an example.

Hi, Tom. Thank You for your help. I glad to research PowerwallCompanion (UWP edition). Also I found PowerwallCompanionX (Xamarin Forms 5- based, only Android target). Great job / Cool projects! You're genius :)  I'm trying to reconstruct ("reforming") PowerwallCompanionX onto some multi-platform app (TeslaX codename; UWP and iOS "targets" added). My goal to run TeslaAuth (and TeslaX) at my old sweet Lumia 950 :)) So, I plan to downgrade .NET Standard from 2.0 to 1.4 (for TeslaAuth library) and switch XF from 5.0 to 2.5.

Tom, did You have:
1) some good SyncFusion Community lic. key?  (SyncFusion blocked my account because I m from RU, heh.... so I start to cancel of SyncFusion's lib. using).
2) some valid Tesla.com account where some old Tesla car (vehicle) added? =)
P.S. I m researched some cool demo-mode in your  PowerwallCompanion (PowerwallCompanionX?) that accepts the showing some demo data for Powerwall deals ))) But I m stupid a little... and I cannot find where I need to tap screen to activate this good feature, because of I not own any Tesla car... =)

Best regards, and sorry for my poor English

**Comment by tomhollander** [comment]
So Powerwall Companion used to run on Windows Phone. I had a forked version of TeslaAuth which works with the older version of .NET - you can still see it in the project history at https://github.com/tomhollander/PowerwallCompanion/tree/70f9a43874a742aa6d63fb96d3d06c75d5c1eed3/PowerwallCompanion/TeslaAuth.

However I had to upgrade the app to newer versions of .NET for a couple of reasons. Tesla introduced a CAPTCHA on the login page which meant I had to abandon my own login page and show the Tesla sign in page in an integrated web browser. And then they changed the login page so it didn't render in the old UWP WebView, so I needed to move to the Chromium WebView2 which does not run on Windows Phone.

Regarding your questions, yes I have both of these things, but no I won't be sharing either of them - sorry!

Tom

**Comment by tomhollander** [comment]
> P.S. I m researched some cool demo-mode in your PowerwallCompanion (PowerwallCompanionX?) that accepts the showing some demo data for Powerwall deals ))) But I m stupid a little... and I cannot find where I need to tap screen to activate this good feature, because of I not own any Tesla car... =)

On the Sign In page, double-click the "Connect To Powerwall" banner to go into demo mode.

**Comment by mediaexplorer74** [comment]
> So Powerwall Companion used to run on Windows Phone. I had a forked version of TeslaAuth which works with the older version of .NET - you can still see it in the project history at https://github.com/tomhollander/PowerwallCompanion/tree/70f9a43874a742aa6d63fb96d3d06c75d5c1eed3/PowerwallCompanion/TeslaAuth.
> 
> However I had to upgrade the app to newer versions of .NET for a couple of reasons. Tesla introduced a CAPTCHA on the login page which meant I had to abandon my own login page and show the Tesla sign in page in an integrated web browser. And then they changed the login page so it didn't render in the old UWP WebView, so I needed to move to the Chromium WebView2 which does not run on Windows Phone.
> 
> Regarding your questions, yes I have both of these things, but no I won't be sharing either of them - sorry!
> 
> Tom

Hi again!

Tom, thank You very much for quick reply from your another timezone =)
Your cool TeslaAuth successfully downgraded to .NET 1.4. 
Look at https://github.com/mediaexplorer74/TeslaX

About credentials: ok, they dont needed very much. I try to find some substitute to SF "framework" (some LiveCharts, etc.). 
As about real Tesla car's "things", I thing your "fake demodata" mode could be enough :) 
 
Andrey
