### ISSUE TITLE
Will not work if you have 2 or more authentificator devices

### ISSUE THREAD

**Issue by bassmaster187** [tomhollander/TeslaAuth#3]
https://github.com/tomhollander/TeslaAuth/blob/628a22e87ea3a244d0d8c8b762c3bbc56dbb0ad6/library/TeslaAuthHelper.cs#L316

**Comment by bassmaster187** [comment]
Check this out: https://github.com/bassmaster187/TeslaLogger/blob/7bbb244721219713e1952297990d645e5c14bdb9/TeslaLogger/WebHelper.cs#L571

**Comment by ramonsmits** [comment]
Added support for it based on that code and is available on https://github.com/ramonsmits/TeslaAuth/tree/multiple-authenticator-support but is currently dependant on other PR's that need to be merged first

**Comment by tomhollander** [comment]
Thanks @ramonsmits - will try to go through all of these later today.
