### ISSUE TITLE
Library not working anymore, authentication returns 403 Forbidden

### ISSUE THREAD

**Issue by gjermshus** [tomhollander/TeslaAuth#34]
Not sure if this is a continuation of #30 or if this is something new. 
Using the library now return 403 Forbidden. The same happens using the `Test.Console`-project as well. I don't have any 2FA activated.
The `Test-WPF`-project works, so the `GetTokenAfterLoginAsync`-function works. But going headless and not letting a web browser login in, is broken.
May it be that Tesla has made new adjustments for unwanted access?

**Comment by tomhollander** [comment]
Hi @gjermshus -

The headless flow has been unreliable for a long time due to CAPTCHAs.  It should probably be removed from the library - I only kept it there in case changes on Tesla's side made it work again. I think the only reliable way to use the library is to use the browser assisted flow.

**Comment by gjermshus** [comment]
Thank you for the response. I will implement it without the headless part.

**Comment by gjermshus** [comment]
By the way. Is there any way to actually obtain the code in a web app? Seems that the limitations in place for cross-site scripting would make sure this is not possible to do from a web app. Since the redirect will never hit the actual caller page and observing the login from a iframe or window popup will also be stopped by the browsers cross site limitations?

**Comment by tomhollander** [comment]
There is a site https://tesla-info.com/tesla-token.php that does this, but I haven't looked into how it works.
