### ISSUE TITLE
RefreshTokenAsync stopped working

### ISSUE THREAD

**Issue by gingertez** [tomhollander/TeslaAuth#35]
Hi,

I'm writing a .NET MAUI app and until today using your TeslaAuth package has worked brilliantly. However today, with no changes to the code, the `RefreshTokenAsync()` method just hangs - no exception, the code just stops on entering the method and doesn't return at all.

I'm using the .NET MAUI `<WebView>` component on my login page and that works fine with TeslaAuth, no issues whatsoever (once I figured out how to clear cookies in it :-) ), it's just the `RefreshTokenAsync()` method that has stopped working. I'm running this on Windows.

I don't know how much of this is down to it being MAUI but it's weird that it has  worked okay for the last couple of weeks and now it doesn't 🤷 

Hopefully Tesla haven't changed their Refresh Token process again but if not do you have any thoughts or ideas on this?

My code around it is pretty simple... I have a local field called `_authTokens` which has the tokens... and it's a one line call from that:
```
        public async Task<bool> RefreshAuthentication()
        {
            try
            {
                var tokens = await _teslaAuth.RefreshTokenAsync(_authTokens.RefreshToken);
                _authTokens.SetTokens(
                    tokens.AccessToken,
                    tokens.RefreshToken,
                    tokens.CreatedAt,
                    tokens.ExpiresIn);

                return true;
            }
            catch (Exception ex)
            {
                throw new Exception("Error refreshing user token", ex);
            }
        }
```
I have verified using Postman that the refresh token does work to get a new access token, it just doesn't work in code for some reason.

Thanks in advance,
Terry.

**Comment by gingertez** [comment]
Update on this: I put the same code into a WinUI 3 app and it works okay. So now I need to figure out why it suddenly stopped working on a MAUI project after working fine for a few weeks.

I've also taken the code from this repo and put it in my app instead of making calls via the Nuget version... and it fails on the `await client.PostAsync("oauth2/v3/token", content);` call. Just disappears into a black hole with no response from the method and no exception.

So it looks like it isn't this repo. Feel free to close this if you agree.

**Comment by tomhollander** [comment]
Thanks @gingertez. I'm not using the library in MAUI myself so I haven't run into it (or heard anyone else complain about issues). If you think there is anything that could change in the code to work around the issue, feel free to make a PR.
