### ISSUE TITLE
System.AggregateException: 'One or more errors occurred. (A task was canceled.)'

### ISSUE THREAD

**Issue by JesperKuipers** [tomhollander/TeslaAuth#6]
The first time I runt the code it worked, after that, I'm not getting responses.
![image](https://user-images.githubusercontent.com/44586411/109167668-4c9eeb00-777e-11eb-8e62-4b142c270cc6.png)

What am I doing wrong here?

**Comment by JesperKuipers** [comment]
@ramonsmits Do you have an idea?

**Comment by ramonsmits** [comment]
@JesperKuipers I do :-) a custom user agent is missing which is required by the tesla api.

**Comment by ramonsmits** [comment]
@JesperKuipers See #8 or my fork at https://github.com/ramonsmits/TeslaAuth/tree/refactorings

**Comment by tomhollander** [comment]
I made some updates (basically, adding more headers, but not User-Agent) which seem to address the problem.
@JesperKuipers can you please try the latest version and let me know if it works?

**Comment by JesperKuipers** [comment]
@tomhollander  ill try it out somewhere this week thanks

**Comment by JesperKuipers** [comment]
Sorry for the late response but it is working rn
